// Generates dist/_headers, the Cloudflare Pages response-header rules (run after
// `vite build`). The rules are boilerplate — identical for every vault, no
// user-specific values — so the PACKAGE owns them and the consumer shell never
// carries the file. Mirrors how the Functions and the 404 are produced at build
// time (see generate-functions.mjs, build-404.mjs), not scaffolded by setup.
//
// Consumer override: if the consumer ships their own public/_headers, `vite
// build` copies it into dist first and this script leaves it untouched.
import { writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { DIST_DIR, PUBLIC_DIR } from './paths.mjs';

const HEADERS = `# GENERATED by web-vault (wv build). Do not edit; this file is a build artifact.
#
# No _redirects file: the app uses hash routing (#/n/...), so there is no SPA
# fallback to configure, and a catch-all rewrite would shadow /shared/*,
# /attachments/* and the /api/* Functions.

# Whole site: security hardening (defense in depth, on top of Cloudflare Access)
# and noindex, so private notes and attachments never enter a search index even
# if a page slips past Access. Shared pages are noindex too, so this is safe.
/*
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  X-Robots-Tag: noindex

# Vite fingerprints asset filenames (content hash), so they can be cached
# forever. Big win on repeat visits.
/assets/*
  Cache-Control: public, max-age=31536000, immutable

# The HTML entry is the ONE file that must never be served stale. It carries the
# entry bundle's hashed name, and that bundle has every lazy chunk's hashed name
# compiled into it. A deploy publishes new hashes and drops the old ones, so a
# cached index.html asks for chunks that no longer exist -> 404 -> a failed
# dynamic import. With no Cache-Control at all the browser falls back to
# heuristic freshness and can hold it for a long time, which is exactly how that
# happens. "no-cache" still stores the file; it just forces revalidation, so an
# unchanged build costs a 304. Do NOT relax /assets/* to match: the pairing of an
# always-revalidated entry with immutable hashed assets is the point.
/
  Cache-Control: no-cache
/index.html
  Cache-Control: no-cache
`;

export const HEADERS_TEXT = HEADERS;

// Consumer override wins: their public/_headers was already copied into dist by
// `vite build`; don't clobber it.
export function buildHeaders({ dist = DIST_DIR, publicDir = PUBLIC_DIR } = {}) {
  if (existsSync(join(publicDir, '_headers'))) return { generated: false };
  writeFileSync(join(dist, '_headers'), HEADERS);
  return { generated: true };
}

// Only run when invoked as a script, so the tests can import buildHeaders().
if (process.argv[1] && process.argv[1].endsWith('build-headers.mjs')) {
  const { generated } = buildHeaders();
  if (generated) {
    console.log('[headers] dist/_headers generated');
  } else {
    // Warn, don't override. The override is a supported escape hatch, but it is
    // all-or-nothing: a consumer file replaces these rules wholesale and so misses
    // every later fix to them — including the no-cache entry rule above, whose
    // absence only shows up as a broken app after some future deploy.
    console.warn(
      '[headers] WARNING: public/_headers found — using it and SKIPPING the ' +
        'generated rules, including no-cache on the HTML entry. Delete it to ' +
        'pick up the current defaults.',
    );
  }
}
