// Generates dist/_headers, the Cloudflare Pages response-header rules (run after
// `vite build`). The rules are boilerplate — identical for every vault, no
// user-specific values — so the PACKAGE owns them and the consumer shell never
// carries the file. Mirrors how the Functions and the 404 are produced at build
// time (see generate-functions.mjs, build-404.mjs), not scaffolded by setup.
//
// Consumer override: if the consumer ships their own public/_headers, `vite
// build` copies it into dist first and this script leaves it untouched.
import { writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { DIST_DIR, PUBLIC_DIR } from './paths.mjs';

const HEADERS = `# GENERATED by web-vault (wv build). Do not edit; this file is a build artifact.
#
# No _redirects file: the app uses hash routing (#/n/...), so there is no SPA
# fallback to configure, and a catch-all rewrite would shadow /shared/*,
# /attachments/* and the /api/* Functions.

# Whole site: security hardening (defense in depth, on top of Cloudflare Access)
# and noindex, so private notes and attachments never enter a search index even
# if a page slips past Access. Shared pages are noindex too, so this is safe.
/*
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  X-Robots-Tag: noindex

# Vite fingerprints asset filenames (content hash), so they can be cached
# forever. Big win on repeat visits.
/assets/*
  Cache-Control: public, max-age=31536000, immutable
`;

// Consumer override wins: their public/_headers was already copied into dist by
// `vite build`; don't clobber it.
if (existsSync(join(PUBLIC_DIR, '_headers'))) {
  console.log('[headers] dist/_headers kept from consumer public/_headers');
} else {
  writeFileSync(join(DIST_DIR, '_headers'), HEADERS);
  console.log('[headers] dist/_headers generated');
}
