// Generates the consumer's Cloudflare Worker entry (.wv/worker.js) as a BUILD
// ARTIFACT (gitignored). It only wires the package factory with build-injected
// config; the logic lives in the package (functions/worker.js +
// functions/commit.js) and upgrades via `yarn up`, so the consumer repo never
// carries Worker code. Workers analogue of the former Pages generate-functions.mjs.
// See adr/0040-cloudflare-workers-deploy-substrate.md.
import './load-env.mjs';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { GEN_DIR, VAULT_DIR } from './paths.mjs';

// owner/name of the vault repo, injected as the handler's default (runtime env
// GITHUB_REPO still wins). Generic: env override, else the git remote.
function detectRepo() {
  const fromEnv = process.env.WEB_VAULT_REPO || process.env.GITHUB_REPO;
  if (fromEnv) return fromEnv;
  try {
    const url = execFileSync('git', ['remote', 'get-url', 'origin'], {
      cwd: VAULT_DIR,
      encoding: 'utf8',
    }).trim();
    const m = url.match(/[:/]([^/:]+\/[^/]+?)(?:\.git)?$/);
    if (m) return m[1];
  } catch {
    /* no remote */
  }
  return '';
}

// The branch the deployment is built from. On Workers Builds this is
// WORKERS_CI_BRANCH; baked so the commit handler targets that same branch
// (runtime env GITHUB_BRANCH still wins). CF_PAGES_BRANCH is kept as a fallback
// for a transitional Pages build, else "main".
const buildBranch = process.env.WORKERS_CI_BRANCH || process.env.CF_PAGES_BRANCH || 'main';
const repo = detectRepo();

mkdirSync(GEN_DIR, { recursive: true });

const config = JSON.stringify({ buildBranch, repo });
writeFileSync(
  join(GEN_DIR, 'worker.js'),
  `// GENERATED by web-vault (wv build). Do not edit; this file is gitignored.\n` +
    `import { makeWorker } from 'web-vault/functions/worker.js';\n` +
    `export default makeWorker(${config});\n`
);
console.log(`[worker] .wv/worker.js (branch ${buildBranch}, repo ${repo || 'n/a'})`);
